services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB:       minitwitter
      POSTGRES_USER:     minitwitter_user
      POSTGRES_PASSWORD: minitwitter_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
