version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB:       minitwitter
      POSTGRES_USER:     minitwitter_user
      POSTGRES_PASSWORD: minitwitter_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build:
      context: .            
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    working_dir: /app
    volumes:
      - ./:/app             
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .            
    command: celery -A config worker --loglevel=info
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  beat:
    build:
      context: .           
    command: celery -A config beat --loglevel=info
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:
